# Neural Embedding Search

We build a semantic search engine using neural embeddings.

Unlike TF-IDF, this method captures meaning, not just keyword overlap.

In [28]:
import sys
print(sys.executable)

/Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/bin/python

In [29]:
import pandas as pd

df = pd.read_csv("../Data/final_tweets.csv")

print(df.shape)
df.head()

(59184, 4)

,tweet_id,text,clean_text,company
0,277379,Another great set of @Delta flights thank to #...,another great set of flights thank to tmobilew...,delta
1,2488664,@AppleSupport why is my iPhone automatically g...,why is my iphone automatically going on mute,applesupport
2,2383194,@Uber_Support Since yesterday I haven't receiv...,since yesterday i havent received any update a...,uber_support
3,1610886,"@AmazonHelp There is no email from 2 days, jus...",there is no email from days just asked to wait...,amazonhelp
4,2763258,"@SouthwestAir thanks for responding, will call...",thanks for responding will call as soon as i g...,southwestair

In [30]:
import sys
!{sys.executable} -m pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from sentence-transformers) (5.7.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from sentence-transformers) (1.13.0)
Requirement already satisfied: torch>=1.11.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from sentence-transformers) (2.11.0)
Requirement already satisfied: numpy>=1.20.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from sentence-transformers) (2.4.4)
Requirement already satisfied: scikit-learn>=0.22.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging>=20.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: joblib>=1.3.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)

In [31]:
from sentence_transformers import SentenceTransformer

In [32]:
!pip install ipywidgets

Requirement already satisfied: ipywidgets in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (8.1.8)
Requirement already satisfied: comm>=0.1.3 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipywidgets) (9.13.0)
Requirement already satisfied: traitlets>=4.3.1 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: decorator>=5.1.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: pexpect>4.6 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: psutil>=7 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (4.15.0)
Requirement already satisfied: wcwidth in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from pexpect>4.6->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in /Users/PREACHERBOYKEYS/TextMiningAndNaturalLanguageProcessingHomeAssignment/nlp-env/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)

In [33]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

print("Model loaded successfully")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Model loaded successfully

In [34]:
search_df = df[["tweet_id", "clean_text", "company"]].copy()

search_df.head()

   tweet_id                                         clean_text       company
0    277379  another great set of flights thank to tmobilew...         delta
1   2488664       why is my iphone automatically going on mute  applesupport
2   2383194  since yesterday i havent received any update a...  uber_support
3   1610886  there is no email from days just asked to wait...    amazonhelp
4   2763258  thanks for responding will call as soon as i g...  southwestair

In [35]:
texts = search_df["clean_text"].tolist()

embeddings = model.encode(texts, show_progress_bar=True)

print("Embeddings shape:", embeddings.shape)

Batches:   0%|          | 0/1850 [00:00<?, ?it/s]

Embeddings shape: (59184, 384)

In [36]:
from sklearn.metrics.pairwise import cosine_similarity

def semantic_search(query, top_k=5):
    # embed query
    query_vec = model.encode([query])
    
    # compute similarity
    scores = cosine_similarity(query_vec, embeddings).flatten()
    
    # get top results
    top_indices = scores.argsort()[::-1][:top_k]
    
    results = search_df.iloc[top_indices].copy()
    results["score"] = scores[top_indices]
    
    return results

In [37]:
semantic_search("flight delayed customer service", top_k=5)

,tweet_id,clean_text,company,score
2472,1799160,flight was already delayed on top of it poor c...,americanair,0.856027
41166,2721339,flight delayed and theres a hr wait on custome...,delta,0.789575
24784,366638,flight delayed hours but no texts no emails no...,delta,0.776327
46536,2258648,been there done that with customer service thr...,americanair,0.773329
36349,2098673,my flight has been delayed hours and no custom...,americanair,0.769100

The neural embedding model captures semantic meaning rather than relying on exact keyword overlap. It retrieves tweets related to flight delays and customer service complaints even when different wording is used, demonstrating improved contextual understanding compared to TF-IDF.